"""Company research primitives exposed through cycle-safe lazy imports."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS = {
    "Migration": "src.research.database",
    "apply_migrations": "src.research.database",
    "backup_database": "src.research.database",
    "restore_database": "src.research.database",
    "schema_version": "src.research.database",
    "verify_integrity": "src.research.database",
    "AlertActionRequest": "src.research.alert_store",
    "MonitorCursor": "src.research.alert_store",
    "ResearchAlert": "src.research.alert_store",
    "ResearchAlertStore": "src.research.alert_store",
    "ChangeReviewRequest": "src.research.change_detection",
    "ResearchChange": "src.research.change_detection",
    "ResearchChangeSet": "src.research.change_detection",
    "detect_research_changes": "src.research.change_detection",
    "ResearchChangeStore": "src.research.change_store",
    "CompanyComparisonRequest": "src.research.comparison",
    "CompanyComparisonResponse": "src.research.comparison",
    "ResearchQueueEntry": "src.research.comparison",
    "ResearchQueueResponse": "src.research.comparison",
    "build_research_queue": "src.research.comparison",
    "compare_company_snapshots": "src.research.comparison",
    "MonitorScanRequest": "src.research.monitor",
    "MonitorScanResponse": "src.research.monitor",
    "TickerScanResult": "src.research.monitor",
    "WatchlistMonitor": "src.research.monitor",
    "PeerGroup": "src.research.peer_groups",
    "PeerGroupInput": "src.research.peer_groups",
    "PeerGroupStore": "src.research.peer_groups",
    "PeerMember": "src.research.peer_groups",
    "ConfirmPostEarningsReviewRequest": "src.research.post_earnings",
    "PostEarningsDraftRequest": "src.research.post_earnings",
    "PostEarningsReviewDraft": "src.research.post_earnings",
    "PostEarningsReviewStore": "src.research.post_earnings",
    "build_post_earnings_review_draft": "src.research.post_earnings",
    "risk_observations_from_report": "src.research.risk_adapter",
    "ChangeType": "src.research.models",
    "FinancialChange": "src.research.models",
    "FinancialMetricPoint": "src.research.models",
    "FinancialSnapshot": "src.research.models",
    "CompanyResearchSnapshot": "src.research.models",
    "ResearchRunManifest": "src.research.models",
    "RiskObservation": "src.research.models",
    "SnapshotComponentResult": "src.research.models",
    "SourceManifestEntry": "src.research.models",
    "FinancialSnapshotBuilder": "src.research.financial_snapshot",
    "FinancialReconciliationReport": "src.research.financial_reconciliation",
    "MetricReconciliation": "src.research.financial_reconciliation",
    "reconcile_financial_snapshot": "src.research.financial_reconciliation",
    "ManagementPeriodSnapshot": "src.research.management_snapshot",
    "ManagementComparisonResponse": "src.research.management_snapshot",
    "ManagementSignalChange": "src.research.management_snapshot",
    "ManagementTopicSignal": "src.research.management_snapshot",
    "RiskFinancialImpact": "src.research.risk_impact",
    "build_management_snapshot": "src.research.management_snapshot",
    "compare_management_snapshots": "src.research.management_snapshot",
    "map_risk_financial_impact": "src.research.risk_impact",
    "ScenarioValuationRequest": "src.research.valuation",
    "ScenarioValuationResponse": "src.research.valuation",
    "ScenarioValuationResult": "src.research.valuation",
    "ValuationScenarioInput": "src.research.valuation",
    "calculate_scenario_valuation": "src.research.valuation",
    "SensitivityCell": "src.research.valuation",
    "SensitivityMatrixRequest": "src.research.valuation",
    "SensitivityMatrixResponse": "src.research.valuation",
    "calculate_sensitivity_matrix": "src.research.valuation",
    "DiscountedCashFlowRequest": "src.research.valuation",
    "DiscountedCashFlowResponse": "src.research.valuation",
    "MultipleValuationRequest": "src.research.valuation",
    "MultipleValuationResponse": "src.research.valuation",
    "calculate_discounted_cash_flow": "src.research.valuation",
    "calculate_multiple_valuation": "src.research.valuation",
    "ExpectationComparison": "src.research.expectations",
    "ExpectationImportResult": "src.research.expectations",
    "ExpectationPoint": "src.research.expectations",
    "ExpectationStore": "src.research.expectations",
    "compare_expectation_to_actual": "src.research.expectations",
    "CompanyResearchOrchestrator": "src.research.orchestrator",
    "ResearchRunRequest": "src.research.orchestrator",
    "ResearchRunResponse": "src.research.orchestrator",
    "ResearchSnapshotStore": "src.research.snapshot_store",
    "Catalyst": "src.research.journal",
    "InvestmentThesis": "src.research.journal",
    "ResearchJournalStore": "src.research.journal",
    "ResearchReminder": "src.research.journal",
    "ThesisReview": "src.research.journal",
    "WatchlistItem": "src.research.journal",
}

__all__ = list(_EXPORTS)


def __getattr__(name: str) -> Any:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
