"""Hypothesis model: research hypotheses generated by the opportunity agent.

These records are research artifacts, not investment recommendations. Every
hypothesis must carry at least one supporting evidence record and is
explicitly flagged as ``not_investment_advice`` by default.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from src.schemas.claims import Claim
from src.schemas.entities import Entity
from src.schemas.evidence import Evidence

HypothesisType = Literal[
    "supply_chain_opportunity",
    "policy_beneficiary",
    "sentiment_turnaround",
    "geopolitical_substitution",
    "risk_mispricing",
    "demand_acceleration",
]


class InvestmentHypothesis(BaseModel):
    """A research hypothesis linking claims, evidence, and entities."""

    model_config = ConfigDict(extra="forbid")

    hypothesis_id: str
    title: str
    hypothesis_type: HypothesisType
    statement: str
    companies: list[Entity]
    graph_paths: list[list[Entity]] = Field(default_factory=list)
    supporting_claims: list[Claim]
    evidence: list[Evidence]
    counter_evidence: list[Evidence] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    watchlist_triggers: list[str] = Field(default_factory=list)
    risks_to_monitor: list[str] = Field(default_factory=list)
    not_investment_advice: bool = True
