import type {
  EvidenceBreakdownItem,
  OverviewRiskRow,
} from "./components/ResearchDecisionBrief";
import type {
  CompanyResearchSnapshot,
  FinancialChange,
  FinancialMetricPoint,
  FinancialSnapshot,
  InvestmentThesis,
  ManagementComparisonResponse,
  ResearchChangeSet,
  ResearchQueueResponse,
  ResearchReminder,
  WatchlistItem,
} from "./types";
import type { SupplyChainSankeyPayloadWire } from "./supply-chain-types";

export const staticOverviewRisks: OverviewRiskRow[] = [
  {
    id: "risk-supply-chain",
    title: "Supply chain concentration",
    summary: "Dependence on limited manufacturing partners and regions",
    score: 72.5,
    trend: [64, 66, 65, 68, 67, 71, 72.5],
    change: 6.2,
    confidence: "High",
  },
  {
    id: "risk-regulatory",
    title: "Regulatory & compliance",
    summary: "Global regulatory scrutiny and data-privacy requirements",
    score: 58,
    trend: [53, 54, 53.5, 55, 55.7, 57, 58],
    change: 2.3,
    confidence: "Medium",
  },
  {
    id: "risk-geopolitical",
    title: "Geopolitical exposure",
    summary: "US–China tensions affecting operations and demand",
    score: 53.1,
    trend: [48, 49.2, 48.8, 50.1, 51, 52.2, 53.1],
    change: 1.7,
    confidence: "Medium",
  },
  {
    id: "risk-demand",
    title: "Demand cyclicality",
    summary: "Consumer spending and product-cycle sensitivity",
    score: 41.6,
    trend: [44, 43.5, 42.9, 43.2, 42.3, 42.1, 41.6],
    change: -0.8,
    confidence: "Medium",
  },
  {
    id: "risk-fx",
    title: "FX exposure",
    summary: "Earnings impact from foreign-exchange volatility",
    score: 32.4,
    trend: [36, 35.6, 34.8, 35.1, 33.7, 33.1, 32.4],
    change: -1.4,
    confidence: "Low",
  },
  {
    id: "risk-ip",
    title: "Intellectual property",
    summary: "IP disputes, licensing costs and infringement risk",
    score: 28.7,
    trend: [30.2, 29.8, 29.2, 29.7, 28.9, 28.8, 28.7],
    change: -0.2,
    confidence: "Low",
  },
];

export const staticEvidenceBreakdown: EvidenceBreakdownItem[] = [
  { label: "High (trusted)", value: 62, color: "#1f7a7a" },
  { label: "Medium (supported)", value: 23, color: "#8ba9ad" },
  { label: "Low (limited)", value: 10, color: "#aab4bd" },
  { label: "Unverified", value: 5, color: "#c2413d" },
];

const metric = (
  name: string,
  value: number,
  unit: string,
  periodKind: FinancialMetricPoint["period_kind"] = "ttm",
  status: FinancialMetricPoint["status"] = "reported",
): FinancialMetricPoint => ({
  metric: name,
  value,
  unit,
  period_end: "2026-06-28",
  period_start: periodKind === "instant" ? null : "2025-06-29",
  period_kind: periodKind,
  fiscal_year: 2026,
  fiscal_period: "Q3",
  form_type: "10-Q",
  accession_number: "0000320193-26-000071",
  filed_at: "2026-07-02T16:30:00Z",
  source_concept: `us-gaap:${name}`,
  status,
  derivation: status === "derived" ? "TTM from reported quarters" : null,
  source_accession_numbers: ["0000320193-26-000071"],
});

const change = (
  name: string,
  current: number,
  previous: number,
  unit: string,
  percent: number,
): FinancialChange => ({
  metric: name,
  change_type: "ttm_yoy",
  current_period_end: "2026-06-28",
  comparison_period_end: "2025-06-29",
  current_value: current,
  comparison_value: previous,
  absolute_change: current - previous,
  percent_change: percent,
  unit,
  source_accession_numbers: ["0000320193-26-000071", "0000320193-25-000079"],
});

export const staticDemoFinancials: FinancialSnapshot = {
  ticker: "AAPL",
  cik: "0000320193",
  company_name: "Apple Inc.",
  as_of: "2026-07-12T12:00:00Z",
  currency: "USD",
  metrics: [
    metric("revenue", 412_300_000_000, "USD", "ttm", "derived"),
    metric("gross_margin", 0.469, "ratio", "ttm", "derived"),
    metric("operating_margin", 0.315, "ratio", "ttm", "derived"),
    metric("net_income", 108_700_000_000, "USD", "ttm", "derived"),
    metric("free_cash_flow", 101_200_000_000, "USD", "ttm", "derived"),
    metric("cash", 67_100_000_000, "USD", "instant"),
    metric("total_debt", 101_800_000_000, "USD", "instant"),
    metric("diluted_shares", 14_920_000_000, "shares", "ttm", "derived"),
  ],
  changes: [
    change("revenue", 412_300_000_000, 391_000_000_000, "USD", 0.054),
    change("gross_margin", 0.469, 0.458, "ratio", 0.024),
    change("operating_margin", 0.315, 0.302, "ratio", 0.043),
    change("net_income", 108_700_000_000, 99_800_000_000, "USD", 0.089),
    change("free_cash_flow", 101_200_000_000, 96_300_000_000, "USD", 0.051),
  ],
  warnings: ["Cash and debt are point-in-time facts; TTM metrics are derived from reported quarters."],
};

export const staticResearchThesis: InvestmentThesis = {
  thesis_id: "thesis-aapl-product-cycle",
  ticker: "AAPL",
  statement: "Services growth and manufacturing diversification can support durable free-cash-flow growth.",
  time_horizon: "12 months",
  status: "active",
  key_drivers: ["services mix", "India manufacturing", "installed base"],
  risks: ["supply-chain concentration", "regulatory pressure"],
  disconfirming_conditions: ["Free cash flow declines for two consecutive quarters", "Services growth falls below hardware growth"],
  monitoring_metrics: ["free_cash_flow", "services_revenue", "gross_margin"],
  catalysts: [],
  evidence_ids: ["10-K-2025", "ev-mgmt-1"],
  reviews: [],
  created_at: "2026-06-30T14:00:00Z",
  updated_at: "2026-07-12T14:32:00Z",
};

export const staticResearchWatchlist: WatchlistItem = {
  ticker: "AAPL",
  thesis_ids: [staticResearchThesis.thesis_id],
  monitoring_questions: ["Is supplier concentration falling without margin dilution?"],
  next_review_date: "2026-07-13",
  active: true,
  updated_at: "2026-07-12T14:32:00Z",
  research_components: ["management", "risks"],
};

export const staticResearchReminder: ResearchReminder = {
  reminder_id: "review-aapl-2026-07-13",
  ticker: "AAPL",
  reminder_type: "thesis_review",
  title: "Review supply-chain evidence change",
  due_date: "2026-07-13",
  overdue: false,
  thesis_id: staticResearchThesis.thesis_id,
};

export const staticResearchSnapshots: CompanyResearchSnapshot[] = [
  {
    snapshot_id: "aapl-2026-q3",
    correlation_id: "static-aapl-demo",
    ticker: "AAPL",
    period: "2026Q3",
    as_of: "2026-07-12T14:32:00Z",
    created_at: "2026-07-12T14:32:00Z",
    source_fingerprint: "aapl-2026-q3-fixture",
    financials: staticDemoFinancials,
    management: null,
    risks: [{ risk_id: "risk-supply-chain", title: "Supply chain concentration", status: "strengthened", severity: "high", evidence_ids: ["10-K-2025", "sc-ev-5"], attributes: { score: 72.5 } }],
    components: [
      { component: "financials", state: "complete", source_count: 2 },
      { component: "management", state: "complete", source_count: 2 },
      { component: "risks", state: "complete", source_count: 3 },
    ],
    sources: [
      { source_id: "10-K-2025", source_type: "sec_filing", provider: "SEC", as_of: "2025-10-31T00:00:00Z", metadata: {} },
      { source_id: "ev-mgmt-1", source_type: "transcript", provider: "fixture", as_of: "2026-07-08T21:00:00Z", metadata: {} },
      { source_id: "sc-ev-5", source_type: "other", provider: "fixture", as_of: "2026-07-12T09:40:00Z", metadata: {} },
    ],
    warnings: [],
  },
  {
    snapshot_id: "aapl-2026-q2",
    ticker: "AAPL",
    period: "2026Q2",
    as_of: "2026-04-30T21:00:00Z",
    created_at: "2026-04-30T21:00:00Z",
    source_fingerprint: "aapl-2026-q2-fixture",
    financials: staticDemoFinancials,
    management: null,
    risks: [{ risk_id: "risk-supply-chain", title: "Supply chain concentration", status: "persistent", severity: "high", evidence_ids: ["10-K-2025"], attributes: { score: 66.3 } }],
    components: [
      { component: "financials", state: "complete", source_count: 2 },
      { component: "management", state: "complete", source_count: 1 },
      { component: "risks", state: "complete", source_count: 1 },
    ],
    sources: [{ source_id: "10-K-2025", source_type: "sec_filing", provider: "SEC", as_of: "2025-10-31T00:00:00Z", metadata: {} }],
    warnings: [],
  },
];

export const staticResearchChanges: ResearchChangeSet = {
  ticker: "AAPL",
  from_snapshot_id: "aapl-2026-q2",
  to_snapshot_id: "aapl-2026-q3",
  generated_at: "2026-07-12T14:32:00Z",
  warnings: [],
  changes: [{
    change_id: "change-supply-chain",
    ticker: "AAPL",
    category: "risk",
    key: "Supply chain concentration",
    status: "strengthened",
    materiality: "high",
    before: { score: 66.3 },
    after: { score: 72.5 },
    before_evidence_ids: ["10-K-2025"],
    after_evidence_ids: ["10-K-2025", "sc-ev-5"],
    detection_method: "evidence-linked score comparison",
    explanation: "Concentration risk rose 6.2 points while manufacturing diversification remains in transition.",
    confidence: 0.88,
    analyst_review_status: "unreviewed",
  }],
};

export const staticResearchQueue: ResearchQueueResponse = {
  entries: [{
    ticker: "AAPL",
    priority: "high",
    reasons: ["Supply-chain concentration strengthened", "One material evidence change needs analyst review"],
    change_ids: ["change-supply-chain"],
    evidence_ids: ["10-K-2025", "sc-ev-5"],
  }],
  disclaimer: "Offline fixture for product demonstration.",
};

export const staticManagementComparison: ManagementComparisonResponse = {
  current: {
    ticker: "AAPL",
    year: 2026,
    quarter: 3,
    transcript_id: "aapl-2026-q3",
    provider: "offline fixture",
    source_url: null,
    published_at: "2026-07-08T21:00:00Z",
    overall_tone: "mixed",
    prepared_remarks_tone: "positive",
    qa_tone: "mixed",
    uncertainty: 0.31,
    defensiveness: 0.22,
    guidance_signal: "maintained",
    topic_signals: [
      { topic: "India manufacturing", sentiment: "positive", confidence: 0.84, evidence_ids: ["ev-mgmt-1"], quotes: ["We continue to expand manufacturing capability in India."] },
      { topic: "China demand", sentiment: "mixed", confidence: 0.76, evidence_ids: ["ev-mgmt-2"], quotes: ["The environment remains competitive."] },
      { topic: "Services", sentiment: "positive", confidence: 0.88, evidence_ids: ["ev-mgmt-3"], quotes: ["Services reached another revenue record."] },
    ],
    evidence_ids: ["ev-mgmt-1", "ev-mgmt-2", "ev-mgmt-3"],
  },
  previous: {
    ticker: "AAPL",
    year: 2026,
    quarter: 2,
    transcript_id: "aapl-2026-q2",
    provider: "offline fixture",
    source_url: null,
    published_at: "2026-04-30T21:00:00Z",
    overall_tone: "positive",
    prepared_remarks_tone: "positive",
    qa_tone: "neutral",
    uncertainty: 0.23,
    defensiveness: 0.17,
    guidance_signal: "maintained",
    topic_signals: [],
    evidence_ids: ["ev-mgmt-prev-1"],
  },
  changes: [
    { dimension: "Q&A uncertainty", previous_value: 0.23, current_value: 0.31, direction: "increased", previous_period: "2026Q2", current_period: "2026Q3", evidence_ids: ["ev-mgmt-2"] },
    { dimension: "India manufacturing", previous_value: "limited detail", current_value: "expanded commitment", direction: "strengthened", previous_period: "2026Q2", current_period: "2026Q3", evidence_ids: ["ev-mgmt-1"] },
  ],
};

export const staticSupplyChain: SupplyChainSankeyPayloadWire = {
  nodes: [
    { node_id: "company:apple", node_type: "company", label: "Apple", normalized_name: "apple", ticker: "AAPL", depth: 0, confidence: 0.99, evidence_ids: ["sc-ev-1"], metadata: { profile: { summary: "Consumer hardware and services company coordinating a globally distributed manufacturing network.", key_items: ["iPhone", "Mac", "Services"], risk_factors: ["regional concentration", "export controls"], confidence: 0.94 } } },
    { node_id: "product:iphone", node_type: "product", label: "iPhone", normalized_name: "iphone", depth: 1, parent_node_id: "company:apple", confidence: 0.98, evidence_ids: ["sc-ev-1"] },
    { node_id: "component:a18", node_type: "component", label: "A18 Pro", normalized_name: "a18-pro", depth: 2, parent_node_id: "product:iphone", confidence: 0.93, evidence_ids: ["sc-ev-2"] },
    { node_id: "company:tsmc", node_type: "company", label: "TSMC", normalized_name: "tsmc", ticker: "TSM", depth: 3, parent_node_id: "component:a18", confidence: 0.94, evidence_ids: ["sc-ev-2"] },
    { node_id: "component:display", node_type: "component", label: "OLED display", normalized_name: "oled-display", depth: 2, parent_node_id: "product:iphone", confidence: 0.88, evidence_ids: ["sc-ev-3"] },
    { node_id: "company:samsung-display", node_type: "company", label: "Samsung Display", normalized_name: "samsung-display", depth: 3, parent_node_id: "component:display", confidence: 0.86, evidence_ids: ["sc-ev-3"] },
    { node_id: "component:memory", node_type: "component", label: "Memory", normalized_name: "memory", depth: 2, parent_node_id: "product:iphone", confidence: 0.84, evidence_ids: ["sc-ev-4"] },
    { node_id: "company:sk-hynix", node_type: "company", label: "SK Hynix", normalized_name: "sk-hynix", depth: 3, parent_node_id: "component:memory", confidence: 0.82, evidence_ids: ["sc-ev-4"] },
    { node_id: "service:assembly", node_type: "service", label: "Final assembly", normalized_name: "final-assembly", depth: 2, parent_node_id: "product:iphone", confidence: 0.91, evidence_ids: ["sc-ev-5"] },
    { node_id: "company:foxconn", node_type: "company", label: "Foxconn", normalized_name: "foxconn", depth: 3, parent_node_id: "service:assembly", confidence: 0.9, evidence_ids: ["sc-ev-5"] },
  ],
  links: [
    ["edge-1", "company:apple", "product:iphone", "requires", 1, 0.99, ["sc-ev-1"]],
    ["edge-2", "product:iphone", "component:a18", "depends_on", 0.92, 0.93, ["sc-ev-2"]],
    ["edge-3", "component:a18", "company:tsmc", "manufactured_by", 0.96, 0.94, ["sc-ev-2"]],
    ["edge-4", "product:iphone", "component:display", "depends_on", 0.78, 0.88, ["sc-ev-3"]],
    ["edge-5", "component:display", "company:samsung-display", "supplied_by", 0.72, 0.86, ["sc-ev-3"]],
    ["edge-6", "product:iphone", "component:memory", "depends_on", 0.62, 0.84, ["sc-ev-4"]],
    ["edge-7", "component:memory", "company:sk-hynix", "supplied_by", 0.58, 0.82, ["sc-ev-4"]],
    ["edge-8", "product:iphone", "service:assembly", "depends_on", 0.89, 0.91, ["sc-ev-5"]],
    ["edge-9", "service:assembly", "company:foxconn", "supplied_by", 0.9, 0.9, ["sc-ev-5"]],
  ].map(([edge_id, source_node_id, target_node_id, relation_type, value, confidence, evidence_ids]) => ({
    edge_id: String(edge_id),
    source_node_id: String(source_node_id),
    target_node_id: String(target_node_id),
    relation_type: relation_type as "requires" | "depends_on" | "manufactured_by" | "supplied_by",
    value: Number(value),
    value_meaning: "importance" as const,
    confidence: Number(confidence),
    evidence_ids: evidence_ids as string[],
  })),
  evidence: [
    { evidence_id: "sc-ev-1", source_type: "filing", source_name: "Apple 10-K", title: "Outsourced manufacturing", quote: "The Company uses outsourcing partners to manufacture subassemblies and finished products.", summary: "Apple relies on a distributed external manufacturing network.", retrieved_at: "2026-07-12T09:00:00Z", published_at: "2025-10-31T00:00:00Z", confidence: 0.95 },
    { evidence_id: "sc-ev-2", source_type: "filing", source_name: "TSMC annual report", title: "Advanced-node manufacturing", quote: "Advanced technologies support high-performance computing and smartphone platforms.", summary: "TSMC is a critical advanced-node manufacturing partner.", retrieved_at: "2026-07-12T09:10:00Z", published_at: "2026-03-10T00:00:00Z", confidence: 0.92 },
    { evidence_id: "sc-ev-3", source_type: "web", source_name: "Supplier disclosure", title: "OLED supply", quote: "OLED capacity supports premium smartphone programs.", summary: "Display supply remains concentrated among a small number of vendors.", retrieved_at: "2026-07-12T09:20:00Z", confidence: 0.82 },
    { evidence_id: "sc-ev-4", source_type: "web", source_name: "Memory supplier filing", title: "Mobile memory", quote: "High-density mobile DRAM supports flagship devices.", summary: "Memory is multi-sourced but still exposed to semiconductor cycles.", retrieved_at: "2026-07-12T09:30:00Z", confidence: 0.78 },
    { evidence_id: "sc-ev-5", source_type: "filing", source_name: "Hon Hai annual report", title: "Electronics assembly", quote: "Consumer smart products remain a major operating segment.", summary: "Foxconn is a significant assembly partner with regional concentration risk.", retrieved_at: "2026-07-12T09:40:00Z", confidence: 0.88 },
  ],
  warnings: ["Fixture relationships illustrate an evidence-linked workflow and are not procurement-spend estimates."],
};
